language: android
android:
  components:
    - build-tools-19.0.3
    - android-19

before_install:
  # for gradle output style
  - export TERM=dumb
  # required libs for android build tools
  #- sudo apt-get update
  #- sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # Set up NDK installation.
  - echo "Android Home: $ANDROID_HOME"
  - echo "Android Platform Tools: `which adb`"
  # export ANDROID_HOME=$(pwd)/android-sdk-linux
  # export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # Download and install newest Android NDK.
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86.tar.bz2 -O ndk.tgz; fi
  - tar -xf ndk.tgz
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r9c
  - export PATH=$PATH:$ANDROID_NDK_HOME

install:
  - pushd $HOME
  - wget https://github.com/psigen/ace/archive/master.zip
  - unzip ./master.zip
  - export ACE_ROOT=`pwd`/ace_master
  - popd

before_script:
  - export MADARA_ROOT=`pwd`
  - export LD_LIBRARY_PATH=$ACE_ROOT/lib:$MADARA_ROOT/lib:$LD_LIBRARY_PATH
  - export PATH=$ACE_ROOT/bin:$MADARA_ROOT/bin:$PATH
  - export PATH=$NDK_BIN:$PATH
  - export CORES=4

script:
  #ACE
  - cd $ACE_ROOT/ace
  - echo "#include \"ace/config-android.h\"" > config.h
  - cd $ACE_ROOT/include/makeinclude
  - echo -e "versioned_so=0\nstatic_libs_only=0\ninclude \$(ACE_ROOT)/include/makeinclude/platform_android.GNU" > platform_macros.GNU
  - cd $ACE_ROOT/ace
  - perl $ACE_ROOT/bin/mwc.pl -type gnuace ace.mwc
  - make -j $CORES
  #MADARA
  - cd $MADARA_ROOT
  - perl $ACE_ROOT/bin/mwc.pl -type gnuace -features java=1,android=1,tests=0 MADARA.mwc
  - make tests=0 java=1 android=1 -j $CORES
